model_params:
  name: 'VanillaVAE'
  in_channels: 3
  latent_dim: 64


data_params:
  data_path: "/home/liyuhang/vae-galaxy/images_training_rev1"
  train_batch_size: 128
  val_batch_size:  64
  patch_size: 128
  num_workers: 4


exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  gpus: [3]
  max_epochs: 20

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"
  
