model_params:
  name: 'VanillaVAE'
  in_channels: 3
  latent_dim: 64


data_params:
  data_path: "/home/liyuhang/dataset/training/images_training_rev1"
  train_batch_size: 128
  val_batch_size:  64
  patch_size: 192
  num_workers: 4


exp_params:
  LR: 0.0025
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  gpus: [0]
  max_epochs: 40

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"
  
